name: TEST
on:
    push:
        branches:
            - main
jobs:
    build_and_upload:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Package Download
              run: npm install

            - name: Test
              run: npm run test